version: '3.3'
services:
  dbCable:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'dbCable'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodata:/data/db
    ports:
     - 27017:27017
volumes:
  mongodata: